### ISSUE TITLE
Status of this package

### ISSUE THREAD

**Issue by jennybc** [gaborcsardi/gh#10]
I'm about to do a lot of work with the GitHub API. Last time I did this was one year ago and I want to re-evaluate my approach in light of new packages. Are you encouraging others to use this package at this point? Or should I look elsewhere?

**Comment by gaborcsardi** [comment]
I think it is stable. The only thing I wanted to test is that all API points return something meaningful. Most of them return JSON, so they are fine, but some of them don't and these need some testing.

Note that this package is very minimal, it hardly gives you more than just using httr by itself.

**Comment by jennybc** [comment]
AFAIK the only real alternative is [`github`](https://github.com/cscheid/rgithub), which is also a very thin wrapper and quite constrained in its evolution because [`rcloud`](https://github.com/att/rcloud) depends on it and is the main reason it exists, I think. It is what I've used in the past.

So perhaps I will give `gh` a try this time around ... Help with de-pagination is something I would love, so that caught my eye.

**Comment by gaborcsardi** [comment]
Btw. if you need sg, please let me know. I am planning to submit this to CRAN, once I manage to write some test cases.
