### ISSUE TITLE
.limit only in force if greater than current page size

### ISSUE THREAD

**Issue by jennybc** [gaborcsardi/gh#24]
Right now `.limit` only comes into force if it is greater than current page size:

``` r
library(gh)
iss_list <- gh("/repos/hadley/dplyr/issues", .limit = 4)
length(iss_list)
#> [1] 30
```

Would you rather change documentation or actually limit the returned output to the first `.limit` results?

**Comment by gaborcsardi** [comment]
Yeah, I remember that I was sloppy with this. What do you think? I guess subsetting is better. If you request 4, you should get 4. Or less. BUt not more at least.

(What actually happens is that even if you request 4 from GH, you might get 30.)

**Comment by jennybc** [comment]
I agree you should get no more than 4 if you asked for 4. I will make another PR unless you wave me off, i.e. would rather do it yourself.

**Comment by gaborcsardi** [comment]
Thanks much, waving off is the last thing I would do. :)
