### ISSUE TITLE
Devtools compatibility

### ISSUE THREAD

**Issue by hadley** [gaborcsardi/gh#29]
It would be nice if gh and devtools could share the same token env var

**Comment by gaborcsardi** [comment]
Indeed, I already decided to do 

```r
token <- Sys.getenv("GITHUB_PAT", NULL) %||% Sys.getenv("GITHUB_TOKEN", NULL)
```

just haven't done it yet.

**Comment by hadley** [comment]
Ok awesome :)

That said, I wonder if longer term we should think about encouraging people to store these in something like the ssh keychain, so you're prompted to unlock them before first use.

**Comment by gaborcsardi** [comment]
Keychain is excellent idea, we would need some fairly portable method to get it from there.
